name: Lint Workflow
 
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  semgrep:
    name: Static analysis with Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1

  hadolint:
    name: Dockerfile analysis with Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile

  super-linter:
    name: Super-Linter
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_MARKDOWN: false
          VALIDATE_DOCKERFILE: false
