name: Unit Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17, 1.18, 1.19]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-deps-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go-version }}-deps-
          ${{ runner.os }}-go-${{ matrix.go-version }}-
          ${{ runner.os }}-
    - name: Run tests
      run: go test ./...
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          your-dockerhub-username/your-image-name:latest
          your-dockerhub-username/your-image-name:${{ matrix.go-version }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_dckr_pat_ShJkbnWpD4VmcmWbq04iGZBsGl4 }}
